#!/bin/bash

trap 'exit' ERR

readonly WEBSITE_DIR="$(readlink -f "$1")"
readonly BUILD_DIR="$(readlink -f "$2")"
readonly BUILD_ARCHIVE="$(readlink -f "$3")"

function minify_html {
    local file="$1"
    echo "Minifying $file..."
    html-minifier \
        --decode-entities \
        --html5 \
        --keep-closing-slash \
        --minify-css \
        --minify-js \
        --remove-comments \
        --remove-redundant-attributes \
        --collapse-whitespace \
        --output "$file" \
        "$file"
}
export -f minify_html

function minify_css {
    local file="$1"
    echo "Minifying $file..."
    cleancss --output "$file" "$file"
}
export -f minify_css


if [[ -d $BUILD_DIR ]]; then
    echo "Build directory already exists" >&2
    exit 1
fi

if [[ -f $BUILD_ARCHIVE ]]; then
    echo "Build archive already exists" >&2
    exit 2
fi

echo "Building $WEBSITE_DIR..."

mkdir "$BUILD_DIR"

# create the directory that could be deployed
rsync -a --exclude '*.psd' --prune-empty-dirs "$WEBSITE_DIR/" "$BUILD_DIR"

# minify
find "$BUILD_DIR" -type f \( -name '*.html' -o -name '*.xhtml' \) \
    -exec bash -c 'minify_html "$0"' {} \;
find "$BUILD_DIR" -type f -name '*.css' -exec bash -c 'minify_css "$0"' {} \;

echo "Distribution created in $BUILD_DIR"

# create a distribution archive for GitHub in case we're building a tag
GZIP=-9 tar -czf "$BUILD_ARCHIVE" -C "$WEBSITE_DIR" .
echo "Distribution archive created at $BUILD_ARCHIVE"
